### ISSUE TITLE
Code has a few errors

### ISSUE THREAD

**Issue by AristotelisPap** [lhao499/HDGE#1]
Hello Hao,

Your paper is really interesting! Could you please consider running your code again and then upload it? In its current state, the results are not reproducible. Even the names of the files are not correct.

Thank you in advance.

Aristotelis-Angelos Papadopoulos

**Comment by haoliuhl** [comment]
Hi Aristotelis! thank you a lot for bringing up this issue! sorry for that I didn't manage to conduct a test run after cleaning up my messy codes! I just fixed the errors, now it should reflect what I did in the paper :) 
I'll run some complete tests to further verify it and release the pertained model, will let you know!
Feel free to email me or reopen the issue if you have further questions, take care!!
