### ISSUE TITLE
This code and pseudo code in paper are not consistent

### ISSUE THREAD

**Issue by chaitanya100100** [lhao499/HDGE#2]
Hi Hao,

Congratulations for coming up with such a simple yet amazing idea!
I have noticed one inconsistency between pseudo code in paper and this code.

[This einsum](https://github.com/lhao499/HDGE/blob/3f3937e271ab3fed2713c55bfe63709df4502c97/model.py#L72) in the code uses `dist` variable which, as per my understanding, is true label distribution (one hot encoding in simple case).

But in the [paper](https://arxiv.org/pdf/2007.09070.pdf) pseudo code, the einsum (mentioned in the first statement of the second column) uses `probs` (predicted distribution) instead of `y` (true distribution).

I think the error lies in paper pseudo code where `probs` should be replaced with `y` in the einsum. Let me know if there is any error in my understanding.

Thank you,
Chaitanya

**Comment by haoliuhl** [comment]
Hi Chaitanya! nice catch!!! will update the pseudo code section in paper to match paper & code.
Thank you very much and take care!
